/*
 * Copyright 2025 Rubens Gomes
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Claude

/**
 * Concrete implementations of error handling interfaces for microservices applications.
 *
 * <p>This package provides production-ready implementations of the error handling contracts defined
 * in the parent {@link com.rubensgomes.msbaselib.error} package. The implementations include both
 * data structures for error representation and comprehensive catalogs of standardized error codes.
 *
 * <h2>Package Overview</h2>
 *
 * <p>The implementation classes in this package are designed to be:
 *
 * <ul>
 *   <li><strong>Production-Ready</strong> - Fully validated, thread-safe implementations
 *   <li><strong>Framework-Agnostic</strong> - Work with Spring, Jakarta EE, or standalone
 *       applications
 *   <li><strong>Validation-Enabled</strong> - Uses Jakarta Bean Validation for data integrity
 *   <li><strong>Extensible</strong> - Easy to extend with custom error codes and implementations
 * </ul>
 *
 * <h2>Core Components</h2>
 *
 * <h3>{@link com.rubensgomes.msbaselib.error.impl.ApplicationErrorImpl}</h3>
 *
 * <p>Concrete implementation of {@link com.rubensgomes.msbaselib.error.ApplicationError}. This
 * class provides a complete, validated data structure for representing application errors with:
 *
 * <ul>
 *   <li><strong>Error Description</strong> - Human-readable error message (mandatory, non-blank)
 *   <li><strong>Error Code</strong> - Structured error code object (mandatory, non-null)
 *   <li><strong>Native Error Text</strong> - Optional system-specific diagnostic information
 * </ul>
 *
 * <p>Key features:
 *
 * <ul>
 *   <li>Lombok @Data annotation for boilerplate reduction
 *   <li>Jakarta Bean Validation constraints for data integrity
 *   <li>Hybrid immutability pattern (core fields immutable, native error text mutable)
 *   <li>Thread-safe for read operations
 * </ul>
 *
 * <h3>{@link com.rubensgomes.msbaselib.error.impl.ApplicationErrorCodeImpl}</h3>
 *
 * <p>Comprehensive enumeration of standardized error codes implementing {@link
 * com.rubensgomes.msbaselib.error.ApplicationErrorCode}. Provides hierarchically organized error
 * codes for common microservices scenarios:
 *
 * <ul>
 *   <li><strong>BUSGN###</strong> - Business Logic Errors: Domain constraints, invalid operation
 *       states
 *   <li><strong>PAYGN###</strong> - Payment Errors: Financial transactions, payment processing
 *   <li><strong>RESGN###</strong> - Resource Management: Resource access, availability, quotas,
 *       rate limits
 *   <li><strong>SECGN###</strong> - Security Errors: Authentication, authorization, session
 *       management
 *   <li><strong>SYSGN###</strong> - System Errors: Infrastructure, database, external services
 *   <li><strong>VALGN###</strong> - Validation Errors: Input validation, format checking, data
 *       integrity
 *   <li><strong>XXXMS###</strong> - Microservice-Specific: Service-specific error codes
 * </ul>
 *
 * <h2>Error Code Naming Convention</h2>
 *
 * <p>Error codes follow a consistent hierarchical naming pattern:
 *
 * <pre>
 * [CATEGORY][TYPE][NUMBER]
 *
 * Where:
 * - CATEGORY: 3-letter error category (BUS, PAY, RES, SEC, SYS, VAL, etc.)
 * - TYPE: 2-letter scope indicator (GN=Generic, MS=MicroService)
 * - NUMBER: 3-digit sequential number (001-999)
 *
 * Examples:
 * - BUSGN001: Business Generic error #001
 * - SECGN003: Security Generic error #003
 * - USRMS001: User Management MicroService error #001
 * </pre>
 *
 * <p>This naming convention provides:
 *
 * <ul>
 *   <li>Easy categorization and grouping of errors
 *   <li>Clear distinction between generic and service-specific errors
 *   <li>Scalability for adding new categories and codes
 *   <li>Consistent programmatic error handling
 * </ul>
 *
 * <h2>Usage Examples</h2>
 *
 * <h3>Creating Error Objects</h3>
 *
 * <pre>{@code
 * // Simple error with just description and code
 * ApplicationError error = new ApplicationErrorImpl(
 *     "User not found",
 *     ApplicationErrorCodeImpl.RESOURCE_NOT_FOUND,
 *     null
 * );
 *
 * // Error with native diagnostic information
 * ApplicationError dbError = new ApplicationErrorImpl(
 *     "Database operation failed",
 *     ApplicationErrorCodeImpl.SYSTEM_DATABASE_ERROR,
 *     "SQLException: Connection timeout after 30s"
 * );
 * }</pre>
 *
 * <h3>Using Error Codes Programmatically</h3>
 *
 * <pre>{@code
 * try {
 *     userService.authenticateUser(credentials);
 * } catch (InvalidCredentialsException e) {
 *     ApplicationError error = new ApplicationErrorImpl(
 *         "Invalid username or password",
 *         ApplicationErrorCodeImpl.SECURITY_INVALID_CREDENTIALS,
 *         e.getMessage()
 *     );
 *     throw new AuthenticationException(error);
 * }
 * }</pre>
 *
 * <h3>Error Categorization for Monitoring</h3>
 *
 * <pre>{@code
 * public void logError(ApplicationError error) {
 *     String errorCode = error.getErrorCode().getCode();
 *
 *     if (errorCode.startsWith("SEC")) {
 *         securityMetrics.incrementSecurityErrors();
 *         alertSecurityTeam(error);
 *     } else if (errorCode.startsWith("SYS")) {
 *         systemMetrics.incrementSystemErrors();
 *         notifyOpsTeam(error);
 *     }
 * }
 * }</pre>
 *
 * <h2>Integration with Frameworks</h2>
 *
 * <h3>Spring Framework Integration</h3>
 *
 * <pre>{@code
 * @RestControllerAdvice
 * public class GlobalExceptionHandler {
 *
 *     @ExceptionHandler(BusinessException.class)
 *     public ResponseEntity<ErrorResponse> handleBusinessException(
 *             BusinessException ex) {
 *         ApplicationError error = new ApplicationErrorImpl(
 *             ex.getMessage(),
 *             ApplicationErrorCodeImpl.BUSINESS_RULE_VIOLATION,
 *             null
 *         );
 *         return ResponseEntity
 *             .status(HttpStatus.BAD_REQUEST)
 *             .body(new ErrorResponse(error));
 *     }
 * }
 * }</pre>
 *
 * <h3>Jakarta EE Integration</h3>
 *
 * <pre>{@code
 * @Provider
 * public class ApplicationExceptionMapper
 *         implements ExceptionMapper<ApplicationException> {
 *
 *     @Override
 *     public Response toResponse(ApplicationException exception) {
 *         ApplicationError error = new ApplicationErrorImpl(
 *             exception.getMessage(),
 *             exception.getErrorCode(),
 *             exception.getCause() != null
 *                 ? exception.getCause().getMessage()
 *                 : null
 *         );
 *         return Response
 *             .status(mapToHttpStatus(error.getErrorCode()))
 *             .entity(error)
 *             .build();
 *     }
 * }
 * }</pre>
 *
 * <h2>Extending with Custom Error Codes</h2>
 *
 * <p>To add service-specific error codes, follow the naming convention:
 *
 * <pre>{@code
 * // In ApplicationErrorCodeImpl enum, add:
 *
 * // Order Management Service (ORDMS###)
 * ORDER_MS_INVALID_ORDER_STATE(
 *     "ORDMS001",
 *     "Order cannot be modified in current state"
 * ),
 * ORDER_MS_PAYMENT_REQUIRED(
 *     "ORDMS002",
 *     "Payment must be completed before order processing"
 * );
 * }</pre>
 *
 * <h2>Thread Safety</h2>
 *
 * <ul>
 *   <li>{@link ApplicationErrorCodeImpl} is thread-safe (enum singleton pattern)
 *   <li>{@link ApplicationErrorImpl} is thread-safe for read operations on immutable fields
 *   <li>Native error text updates in {@link ApplicationErrorImpl} require external synchronization
 *       for concurrent modifications
 * </ul>
 *
 * <h2>Validation</h2>
 *
 * <p>All implementations use Jakarta Bean Validation:
 *
 * <ul>
 *   <li>@NotBlank ensures non-null, non-empty strings with meaningful content
 *   <li>@NotNull ensures required object references are provided
 *   <li>@Nullable explicitly marks optional fields
 * </ul>
 *
 * <h2>Best Practices</h2>
 *
 * <ul>
 *   <li>Use appropriate error codes that match the actual error condition
 *   <li>Provide clear, user-friendly error descriptions
 *   <li>Include native error text for debugging, but sanitize sensitive information
 *   <li>Map error codes to appropriate HTTP status codes in REST APIs
 *   <li>Log errors with full context including native error details
 *   <li>Monitor error patterns to identify system issues
 * </ul>
 *
 * @author Rubens Gomes
 * @since 0.0.1
 * @see com.rubensgomes.msbaselib.error
 * @see com.rubensgomes.msbaselib.error.ApplicationError
 * @see com.rubensgomes.msbaselib.error.ApplicationErrorCode
 * @see lombok.Data
 * @see jakarta.validation.constraints
 */
package com.rubensgomes.msbaselib.error.impl;
