/*
 * Copyright 2025 Rubens Gomes
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Claude

/**
 * Core base types and foundational components for microservices applications.
 *
 * <p>This package provides essential base types, enumerations, and foundational interfaces that are
 * commonly shared across microservices architectures. These components establish standardized
 * patterns for request/response handling, status reporting, and error management in distributed
 * systems.
 *
 * <h2>Package Overview</h2>
 *
 * <p>The core components in this package serve as building blocks for consistent communication and
 * state management across microservices. They are designed to be:
 *
 * <ul>
 *   <li><strong>Technology-Agnostic</strong> - Can be used with any framework or transport protocol
 *   <li><strong>Thread-Safe</strong> - Safe for use in concurrent and distributed environments
 *   <li><strong>Immutable</strong> - Enum-based designs ensure thread safety and consistency
 *   <li><strong>Well-Documented</strong> - Comprehensive Javadoc for all public APIs
 * </ul>
 *
 * <h2>Core Components</h2>
 *
 * <h3>{@link com.rubensgomes.msbaselib.Status}</h3>
 *
 * <p>Enumeration representing the lifecycle status or outcome of operations in microservices
 * architectures. Provides standardized status values for both synchronous and asynchronous
 * processing patterns:
 *
 * <ul>
 *   <li><strong>Success States:</strong> {@link com.rubensgomes.msbaselib.Status#SUCCESS}, {@link
 *       com.rubensgomes.msbaselib.Status#COMPLETED}
 *   <li><strong>Failure States:</strong> {@link com.rubensgomes.msbaselib.Status#FAILURE}, {@link
 *       com.rubensgomes.msbaselib.Status#ERROR}, {@link com.rubensgomes.msbaselib.Status#TIMEOUT},
 *       {@link com.rubensgomes.msbaselib.Status#ABORTED}
 *   <li><strong>Progress States:</strong> {@link com.rubensgomes.msbaselib.Status#PENDING}, {@link
 *       com.rubensgomes.msbaselib.Status#PROCESSING}
 *   <li><strong>Termination States:</strong> {@link com.rubensgomes.msbaselib.Status#CANCELLED}
 * </ul>
 *
 * <p>The Status enum supports comprehensive monitoring, error tracking, and workflow management in
 * distributed systems.
 *
 * <h2>Related Packages</h2>
 *
 * <ul>
 *   <li>{@link com.rubensgomes.msbaselib.error} - Comprehensive error handling and error code
 *       management framework
 *   <li>{@link com.rubensgomes.msbaselib.error.impl} - Concrete implementations of error handling
 *       interfaces
 * </ul>
 *
 * <h2>Usage Patterns</h2>
 *
 * <h3>Synchronous Operations</h3>
 *
 * <p>For immediate request/response patterns:
 *
 * <pre>{@code
 * public Response processRequest(Request request) {
 *     try {
 *         Result result = service.process(request);
 *         return new Response(Status.SUCCESS, result);
 *     } catch (ValidationException e) {
 *         return new Response(Status.FAILURE, null, e.getMessage());
 *     } catch (Exception e) {
 *         return new Response(Status.ERROR, null, e.getMessage());
 *     }
 * }
 * }</pre>
 *
 * <h3>Asynchronous Operations</h3>
 *
 * <p>For long-running or queued operations:
 *
 * <pre>{@code
 * public Response submitTask(TaskRequest request) {
 *     String taskId = taskService.submit(request);
 *     return new Response(Status.PENDING, taskId);
 * }
 *
 * public Response pollTaskStatus(String taskId) {
 *     TaskStatus taskStatus = taskService.getStatus(taskId);
 *     Status status = mapTaskStatusToStatus(taskStatus);
 *     return new Response(status, taskStatus.getProgress());
 * }
 * }</pre>
 *
 * <h2>Integration Notes</h2>
 *
 * <ul>
 *   <li>Use these base types across all microservices for consistent API responses
 *   <li>Integrate with monitoring systems for comprehensive observability
 *   <li>Combine with error handling components for complete error management
 *   <li>Follow microservices best practices for distributed system design
 * </ul>
 *
 * <h2>Design Principles</h2>
 *
 * <p>This package follows key design principles:
 *
 * <ul>
 *   <li><strong>SOLID Principles</strong> - Clear separation of concerns and single responsibility
 *   <li><strong>Clean Code</strong> - Clarity over cleverness, meaningful names, comprehensive
 *       documentation
 *   <li><strong>Immutability</strong> - Enum-based designs ensure thread safety
 *   <li><strong>Fail-Fast</strong> - Early validation and clear error reporting
 * </ul>
 *
 * @author Rubens Gomes
 * @since 0.0.1
 * @see com.rubensgomes.msbaselib.Status
 * @see com.rubensgomes.msbaselib.error
 */
package com.rubensgomes.msbaselib;
